bundler_args: --without development
script: "bundle exec rake spec:ci"
before_script: ./bin/ci/before_build.sh
notifications:
  disabled: true
rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - jruby
  - rbx
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
