bundler_args: --without development
script: "bundle exec rake spec:ci"
notifications:
  disabled: true
rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - jruby
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
